apiVersion: v1
kind: Pod
metadata:
  name: busybox-container-defaultns
spec:
  containers:
  - name: busybox-container
    image: busybox
    env:
    - name: azure-keyvault-dawidappns
      valueFrom:
        secretKeyRef:
          key: username
          name: azure-keyvault-test-secret
