apiVersion: v1
kind: Pod
metadata:
  name: php-mysql-app
spec:
  containers:
  - env:
    - name: azure-keyvault-default
      valueFrom:
        secretKeyRef:
          key: username
          name: azure-keyvault-test-secret
